<!DOCTYPE html>
<html lang="en">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8">
	<link rel="stylesheet" href="css/styles.css">
	
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
	<script src="js/banner.js"></script>
	<script src="js/nav.js"></script>

	<title>Social</title>
</head>
<body>
	<div>
			<div>
		<div id="topNav" class="topBar">
		
				<div class="btnCon">
					<button class="trending">Trending</button>
				</div>

				<a class="homeAnchor" href='index.html'> 
					<div class="home">	
						<img class="nav_hamburger" src="images/home.png">
					</div>
				</a>	

				<div class="hamburger_con">
					<img class="nav_hamburger" src="images/hamburger.png">
				<!-- 	<img class="nav_hamburger" src="images/x-maybe.png"> -->
				</div>


			
		</div>
	</div>
	</div>

	
	<div class="navigation">

		<div class="menuTop"> 
			<h3>Menu</h3>
		</div>

		<div class="navBtn">
			<div class="expandTrig"> 
				<h4>Flower</h4> 
				<img class="arrowImg" src="images/navigation-arrow.png">
			</div>	 
			<div class="subMenu">
				<!-- <a href='greenGallery.html'>  -->
			<!-- 		<div class="submenuCat">
						<img src="images/gallery-icon.png"> 
						<h5>Gallery</h5>
					</div> -->
			<!-- 	</a> -->
				<a href='greenMenu.html'> 
					<div class="submenuCat">
						<img src="images/description-icon.png"> 	 
						<h5>Menu</h5> 
					</div>
				</a>		
			</div> 
		</div>

		<div class="navBtn"> 
			<div class="expandTrig"> 
				<h4>Dabs</h4> 
				<img class="arrowImg" src="images/navigation-arrow.png"> 
			</div>	
			<div class="subMenu"> 
	<!-- 			<div class="submenuCat">
					<img src="images/gallery-icon.png"> 
					<h5>Gallery</h5>
				</div> -->
				<a href='oilMenu.html'> 
					<div class="submenuCat">
						<img src="images/description-icon.png"> 	 
						<h5>Menu</h5> 
					</div>
				</a>		
			</div> 
		</div>

		<div class="navBtn"> 
			<div class="expandTrig"> 
				<h4>Other Products</h4> 
				<img class="arrowImg" src="images/navigation-arrow.png"> 
			</div>	
			<div class="subMenu"> 
	<!-- 			<div class="submenuCat">
					<img src="images/gallery-icon.png"> 
					<h5>Gallery</h5>pictures in circle div not showing up on m
				</div> -->
				<div class="submenuCat">
					<img src="images/description-icon.png"> 	 
					<h5>Menu</h5> 
				</div>	
			</div> 
		</div>
		<div class="bottomNav"></div>
	</div>

	<div id="main">
		<div>
			<h2>Green Social</h2>
		</div>

	</div>

</body>
</html>
